title = "Wilson Villalba"
baseURL = "/"
languageCode = "es"
theme = ["hugo-embed-pdf-shortcode", "ananke", "github.com/hugomods/utterances"]
enableInlineShortcodes = true
#resourceDir = "../resources"

DefaultContentLanguage = "es"
SectionPagesMenu = "main"
Paginate = 6 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true


    #[taxonomies]
    #author = "authors"

[menu]

  [[menu.main]]
    identifier = 'villalba.is'
    name = 'villalba.is'
    url = 'https://villalba.is'
    weight = 90
  [[menu.main]]
    identifier = '0007407.xyz'
    name = '0007407.xyz'
    url = 'https://0007407.xyz'
    weight = 100


    #[[menu.main]]
    #  identifier = 'about'
    #  name = 'about'
    #  pageRef = '/about'
    #  weight = 20
    #[[menu.main]]
    #  identifier = 'posts'
    #  name = 'plra'
    #  pageRef = '/plra'
    #  weight = 30
    #[[menu.main]]
    #  identifier = 'archivo'
    #  name = 'archivo'
    #  pageRef = '/archivo'
    #  weight = 40

    

[languages]

  [languages.es]
    title = "Wilson Villalba"
    description = "Litigios"
    weight = 1
    contentDir = "content/es"
  # languageDirection = 'rtl' for Right-To-Left languages

  #[languages.fr]
  #  title = "Ananke Fr"
  #  weight = 2
  #  contentDir = "content/fr"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = "Wilson Villalba"
  favicon = "vvv.svg"
  site_logo = "vvv.svg"
  description = "Litigios."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-blue"
  recent_posts_number = 3
  post_content_classes = "athelas"
  body_classes = "times"
  feature_image = "cover.jpg"
  mainSections = ['posts', 'modelos']

[[params.ananke_socials]]
  name = "telegram"
  url = "https://t.me/habermas"

[params.utterances]
        # Client script endpoint.
        endpoint = "https://utteranc.es/"

        # The GitHub repository, required.
        repo = "hugomods/utterances"

        # The mapping between blog posts and GitHub issues. Available options:
        #   pathname: Utterances will search for an issue whose title contains the blog post's pathname URL component.
        #   url:      Utterances will search for an issue whose title contains the blog post's URL.
        #   title:    Utterances will search for an issue whose title contains the blog post's title.
        #   og:title: Utterances will search for an issue whose title contains the page's Open Graph title meta.
        mapping = "day-begins"

        # The label that will be assigned to issues created by Utterances.
        label = "Comentarios"

        # Theme. Available options:
        #   github-light:           GitHub Light
        #   github-dark:            GitHub Dark
        #   preferred-color-scheme: Preferred Color Scheme
        #   github-dark-orange:     GitHub Dark Orange
        #   icy-dark:               Icy Dark
        #   dark-blue:              Dark Blue
        #   photon-dark:            Photon Dark
        #   boxy-light:             Boxy Light
        #   gruvbox-dark:           Gruvbox Dark
        theme = "icy-dark"

